port: 3000
scraper:
  base_url: http://www.loveroms.com
  interval: '10 mins'
data_dir: ./data
download_dir: /home/pi/RetroPie/roms
consoles:
  - title: Gameboy Advance
    lr: gameboy-advance
    rp: gba
  - title: Atari 2600
    lr: atari-2600
    rp: atari2600